import Decimal from 'decimal.js'
import { D } from '../../core/bignum'
import type { MonsterTemplate } from '../../types'

export const MONSTER_TEMPLATES: Record<string, MonsterTemplate> = {
  // ── Tier 1 怪物（草原/起始區域 Lv1-10）──────────────
  slime: {
    id: 'slime', name: '黏液史萊姆', family: 'slime', tier: 1, isBoss: false, isElite: false,
    description: '最常見的入門怪物，身體柔軟但有酸性。',
    baseStats: {
      hp: D(30), mp: D(0),
      atk: D(5), def: D(2),
      matk: D(0), mdef: D(1),
      spd: D(3), lck: D(1),
      crit: D('0.03'), critDmg: D('1.5'),
      dodge: D('0.02'), acc: D('0.9'),
    },
    statScaling: 1.0,
    skillIds: [],
    lootTable: [{ templateId: 'iron_sword', weight: 0.05, minQty: 1, maxQty: 1 }],
    goldDrop: [3, 12],
    xpReward: D(150),
    tameable: true, tameRate: 0.3,
  },
  goblin: {
    id: 'goblin', name: '哥布林', family: 'humanoid', tier: 1, isBoss: false, isElite: false,
    description: '成群結隊的小型惡棍，善於偷竊。',
    baseStats: {
      hp: D(45), mp: D(5),
      atk: D(8), def: D(3),
      matk: D(2), mdef: D(2),
      spd: D(7), lck: D(5),
      crit: D('0.05'), critDmg: D('1.6'),
      dodge: D('0.08'), acc: D('0.9'),
    },
    statScaling: 1.0,
    skillIds: [],
    lootTable: [{ templateId: 'leather_cap', weight: 0.08, minQty: 1, maxQty: 1 }],
    goldDrop: [6, 20],
    xpReward: D(250),
    tameable: true, tameRate: 0.2,
  },
  wolf: {
    id: 'wolf', name: '野狼', family: 'beast', tier: 1, isBoss: false, isElite: false,
    description: '草原上的捕食者，行動迅速。',
    baseStats: {
      hp: D(60), mp: D(0),
      atk: D(12), def: D(4),
      matk: D(0), mdef: D(2),
      spd: D(12), lck: D(3),
      crit: D('0.08'), critDmg: D('1.8'),
      dodge: D('0.1'), acc: D('0.92'),
    },
    statScaling: 1.1,
    skillIds: [],
    lootTable: [{ templateId: 'short_sword', weight: 0.06, minQty: 1, maxQty: 1 }],
    goldDrop: [10, 25],
    xpReward: D(350),
    tameable: true, tameRate: 0.15,
  },
  // ── Tier 1.5 怪物（哥布林谷 Lv8-15）───────────────
  goblin_warrior: {
    id: 'goblin_warrior', name: '哥布林戰士', family: 'humanoid', tier: 1, isBoss: false, isElite: false,
    description: '裝備了劣質武器的哥布林精銳。',
    baseStats: {
      hp: D(80), mp: D(0),
      atk: D(15), def: D(8),
      matk: D(0), mdef: D(3),
      spd: D(8), lck: D(4),
      crit: D('0.06'), critDmg: D('1.7'),
      dodge: D('0.06'), acc: D('0.9'),
    },
    statScaling: 1.1,
    skillIds: [],
    lootTable: [{ templateId: 'iron_sword', weight: 0.1, minQty: 1, maxQty: 1 }],
    goldDrop: [12, 30],
    xpReward: D(400),
    tameable: true, tameRate: 0.12,
  },
  cave_bat: {
    id: 'cave_bat', name: '洞穴蝙蝠', family: 'beast', tier: 1, isBoss: false, isElite: false,
    description: '洞穴中成群飛翔的吸血蝙蝠。',
    baseStats: {
      hp: D(55), mp: D(0),
      atk: D(10), def: D(2),
      matk: D(0), mdef: D(3),
      spd: D(18), lck: D(6),
      crit: D('0.1'), critDmg: D('1.8'),
      dodge: D('0.15'), acc: D('0.88'),
    },
    statScaling: 1.0,
    skillIds: [],
    lootTable: [],
    goldDrop: [8, 18],
    xpReward: D(300),
    tameable: true, tameRate: 0.1,
  },
  // ── Tier 2 怪物（沼澤/山脈 Lv15-35）──────────────
  skeleton: {
    id: 'skeleton', name: '骷髏士兵', family: 'undead', tier: 2, isBoss: false, isElite: false,
    description: '被詛咒的亡者，以骨頭為甲。',
    baseStats: {
      hp: D(80), mp: D(0),
      atk: D(18), def: D(12),
      matk: D(0), mdef: D(5),
      spd: D(6), lck: D(2),
      crit: D('0.05'), critDmg: D('1.7'),
      dodge: D('0.03'), acc: D('0.88'),
    },
    statScaling: 1.2,
    skillIds: [],
    lootTable: [{ templateId: 'iron_sword', weight: 0.1, minQty: 1, maxQty: 1 }, { templateId: 'iron_helm', weight: 0.08, minQty: 1, maxQty: 1 }],
    goldDrop: [15, 40],
    xpReward: D(500),
    tameable: false, tameRate: 0,
  },
  poison_toad: {
    id: 'poison_toad', name: '毒蟾蜍', family: 'beast', tier: 2, isBoss: false, isElite: false,
    description: '沼澤中的劇毒蟾蜍，吐出致命的毒液。',
    baseStats: {
      hp: D(100), mp: D(40),
      atk: D(14), def: D(6),
      matk: D(20), mdef: D(10),
      spd: D(6), lck: D(4),
      crit: D('0.05'), critDmg: D('1.6'),
      dodge: D('0.05'), acc: D('0.88'),
    },
    statScaling: 1.2,
    skillIds: [],
    lootTable: [{ templateId: 'cloth_robe', weight: 0.06, minQty: 1, maxQty: 1 }],
    goldDrop: [18, 45],
    xpReward: D(600),
    tameable: true, tameRate: 0.08,
  },
  orc: {
    id: 'orc', name: '獸人戰士', family: 'humanoid', tier: 2, isBoss: false, isElite: false,
    description: '強壯有力的戰鬥種族，崇尚武力。',
    baseStats: {
      hp: D(120), mp: D(0),
      atk: D(25), def: D(15),
      matk: D(0), mdef: D(5),
      spd: D(5), lck: D(3),
      crit: D('0.06'), critDmg: D('2.0'),
      dodge: D('0.05'), acc: D('0.88'),
    },
    statScaling: 1.3,
    skillIds: [],
    lootTable: [{ templateId: 'iron_armor', weight: 0.1, minQty: 1, maxQty: 1 }],
    goldDrop: [20, 55],
    xpReward: D(700),
    tameable: true, tameRate: 0.1,
  },
  swamp_witch: {
    id: 'swamp_witch', name: '沼澤女巫', family: 'humanoid', tier: 2, isBoss: false, isElite: false,
    description: '施展詛咒魔法的沼澤居民，藥水達人。',
    baseStats: {
      hp: D(90), mp: D(120),
      atk: D(8), def: D(6),
      matk: D(32), mdef: D(18),
      spd: D(9), lck: D(10),
      crit: D('0.09'), critDmg: D('2.0'),
      dodge: D('0.07'), acc: D('0.91'),
    },
    statScaling: 1.25,
    skillIds: [],
    lootTable: [{ templateId: 'magic_staff', weight: 0.1, minQty: 1, maxQty: 1 }],
    goldDrop: [22, 60],
    xpReward: D(750),
    tameable: false, tameRate: 0,
  },
  stone_golem: {
    id: 'stone_golem', name: '石像魔像', family: 'construct', tier: 2, isBoss: false, isElite: false,
    description: '以山石凝聚而成的魔法構造體，皮硬難傷。',
    baseStats: {
      hp: D(200), mp: D(0),
      atk: D(22), def: D(30),
      matk: D(0), mdef: D(10),
      spd: D(3), lck: D(1),
      crit: D('0.03'), critDmg: D('1.8'),
      dodge: D('0.01'), acc: D('0.85'),
    },
    statScaling: 1.3,
    skillIds: [],
    lootTable: [{ templateId: 'iron_armor', weight: 0.12, minQty: 1, maxQty: 1 }],
    goldDrop: [25, 65],
    xpReward: D(800),
    tameable: false, tameRate: 0,
  },
  // ── Tier 3 怪物（鐵山/黑暗森林 Lv35-60）──────────
  iron_sentinel: {
    id: 'iron_sentinel', name: '鐵甲守衛', family: 'construct', tier: 3, isBoss: false, isElite: false,
    description: '鐵山礦脈的守護機械，全身金屬鎧甲。',
    baseStats: {
      hp: D(300), mp: D(0),
      atk: D(45), def: D(50),
      matk: D(0), mdef: D(20),
      spd: D(7), lck: D(3),
      crit: D('0.05'), critDmg: D('1.8'),
      dodge: D('0.02'), acc: D('0.9'),
    },
    statScaling: 1.4,
    skillIds: [],
    lootTable: [{ templateId: 'steel_helm', weight: 0.1, minQty: 1, maxQty: 1 }],
    goldDrop: [40, 100],
    xpReward: D(1200),
    tameable: false, tameRate: 0,
  },
  thunder_hawk: {
    id: 'thunder_hawk', name: '雷鷹', family: 'beast', tier: 3, isBoss: false, isElite: false,
    description: '操控雷電的巨鷹，俯衝時能引發閃電。',
    baseStats: {
      hp: D(220), mp: D(80),
      atk: D(38), def: D(20),
      matk: D(35), mdef: D(25),
      spd: D(25), lck: D(8),
      crit: D('0.12'), critDmg: D('2.1'),
      dodge: D('0.12'), acc: D('0.93'),
    },
    statScaling: 1.4,
    skillIds: [],
    lootTable: [],
    goldDrop: [45, 110],
    xpReward: D(1300),
    tameable: true, tameRate: 0.06,
  },
  dark_mage: {
    id: 'dark_mage', name: '黑暗法師', family: 'humanoid', tier: 3, isBoss: false, isElite: false,
    description: '操控黑暗魔法的危險術士。',
    baseStats: {
      hp: D(100), mp: D(150),
      atk: D(10), def: D(8),
      matk: D(40), mdef: D(20),
      spd: D(10), lck: D(8),
      crit: D('0.1'), critDmg: D('2.2'),
      dodge: D('0.08'), acc: D('0.93'),
    },
    statScaling: 1.4,
    skillIds: ['skill_fireball'],
    lootTable: [{ templateId: 'magic_staff', weight: 0.12, minQty: 1, maxQty: 1 }],
    goldDrop: [50, 120],
    xpReward: D(1200),
    tameable: true, tameRate: 0.08,
  },
  // ── Tier 4 怪物（火山 Lv60-80）────────────────────
  lava_elemental: {
    id: 'lava_elemental', name: '熔岩元素', family: 'elemental', tier: 4, isBoss: false, isElite: false,
    description: '由滾燙岩漿凝聚而成的元素生命。',
    baseStats: {
      hp: D(450), mp: D(200),
      atk: D(60), def: D(40),
      matk: D(80), mdef: D(50),
      spd: D(10), lck: D(6),
      crit: D('0.08'), critDmg: D('2.1'),
      dodge: D('0.05'), acc: D('0.91'),
    },
    statScaling: 1.5,
    skillIds: [],
    lootTable: [{ templateId: 'fire_staff', weight: 0.08, minQty: 1, maxQty: 1 }],
    goldDrop: [80, 200],
    xpReward: D(2200),
    tameable: false, tameRate: 0,
  },
  fire_drake: {
    id: 'fire_drake', name: '火焰飛蜥', family: 'dragon', tier: 4, isBoss: false, isElite: false,
    description: '能噴吐火焰的爬行龍族，遠古龍的遠親。',
    baseStats: {
      hp: D(380), mp: D(100),
      atk: D(70), def: D(35),
      matk: D(55), mdef: D(30),
      spd: D(18), lck: D(9),
      crit: D('0.1'), critDmg: D('2.2'),
      dodge: D('0.08'), acc: D('0.92'),
    },
    statScaling: 1.5,
    skillIds: [],
    lootTable: [{ templateId: 'cursed_blade', weight: 0.07, minQty: 1, maxQty: 1 }],
    goldDrop: [100, 250],
    xpReward: D(2500),
    tameable: true, tameRate: 0.04,
  },
  inferno_ogre: {
    id: 'inferno_ogre', name: '烈焰巨人', family: 'humanoid', tier: 4, isBoss: false, isElite: false,
    description: '被火山熔岩灼燒過的巨人，皮膚如同岩石。',
    baseStats: {
      hp: D(600), mp: D(0),
      atk: D(90), def: D(60),
      matk: D(20), mdef: D(30),
      spd: D(8), lck: D(5),
      crit: D('0.07'), critDmg: D('2.3'),
      dodge: D('0.04'), acc: D('0.88'),
    },
    statScaling: 1.6,
    skillIds: [],
    lootTable: [{ templateId: 'mountain_hammer', weight: 0.08, minQty: 1, maxQty: 1 }],
    goldDrop: [120, 300],
    xpReward: D(2800),
    tameable: false, tameRate: 0,
  },
  dragon_hatchling: {
    id: 'dragon_hatchling', name: '幼龍', family: 'dragon', tier: 4, isBoss: false, isElite: false,
    description: '年幼的龍族，已展現出驚人的戰鬥力。',
    baseStats: {
      hp: D(500), mp: D(200),
      atk: D(80), def: D(50),
      matk: D(60), mdef: D(40),
      spd: D(15), lck: D(10),
      crit: D('0.12'), critDmg: D('2.3'),
      dodge: D('0.1'), acc: D('0.95'),
    },
    statScaling: 1.6,
    skillIds: [],
    lootTable: [{ templateId: 'dragon_fang', weight: 0.05, minQty: 1, maxQty: 1 }],
    goldDrop: [150, 400],
    xpReward: D(3500),
    tameable: true, tameRate: 0.05,
    evolveToId: 'young_dragon', evolveLevelReq: 50,
  },
  // ── Tier 5 怪物（龍峰 Lv80-100）──────────────────
  crystal_goliath: {
    id: 'crystal_goliath', name: '水晶巨像', family: 'construct', tier: 5, isBoss: false, isElite: false,
    description: '由純淨水晶構成的巨大守衛，反射所有魔法。',
    baseStats: {
      hp: D(1200), mp: D(0),
      atk: D(130), def: D(120),
      matk: D(0), mdef: D(150),
      spd: D(6), lck: D(5),
      crit: D('0.05'), critDmg: D('2.0'),
      dodge: D('0.02'), acc: D('0.88'),
    },
    statScaling: 1.7,
    skillIds: [],
    lootTable: [{ templateId: 'dragon_scale_armor', weight: 0.04, minQty: 1, maxQty: 1 }],
    goldDrop: [200, 500],
    xpReward: D(5000),
    tameable: false, tameRate: 0,
  },
  ancient_lich: {
    id: 'ancient_lich', name: '遠古骷髏法師', family: 'undead', tier: 5, isBoss: false, isElite: false,
    description: '突破生死界限的不死術士，掌控強大的死亡魔法。',
    baseStats: {
      hp: D(800), mp: D(600),
      atk: D(50), def: D(60),
      matk: D(180), mdef: D(120),
      spd: D(14), lck: D(20),
      crit: D('0.15'), critDmg: D('2.5'),
      dodge: D('0.1'), acc: D('0.95'),
    },
    statScaling: 1.7,
    skillIds: [],
    lootTable: [{ templateId: 'dragon_fang', weight: 0.06, minQty: 1, maxQty: 1 }],
    goldDrop: [250, 600],
    xpReward: D(5500),
    tameable: false, tameRate: 0,
  },
  young_dragon: {
    id: 'young_dragon', name: '亞成體龍', family: 'dragon', tier: 5, isBoss: false, isElite: false,
    description: '正值壯年的龍族，力量和魔法俱強。',
    baseStats: {
      hp: D(1500), mp: D(500),
      atk: D(150), def: D(100),
      matk: D(130), mdef: D(90),
      spd: D(20), lck: D(15),
      crit: D('0.14'), critDmg: D('2.5'),
      dodge: D('0.1'), acc: D('0.96'),
    },
    statScaling: 1.8,
    skillIds: [],
    lootTable: [{ templateId: 'dragon_fang', weight: 0.08, minQty: 1, maxQty: 1 }],
    goldDrop: [350, 800],
    xpReward: D(7000),
    tameable: true, tameRate: 0.03,
  },
  // ── BOSS ──────────────────────────────────────────
  goblin_king: {
    id: 'goblin_king', name: '哥布林王', family: 'humanoid', tier: 2, isBoss: true, isElite: false,
    description: '統率哥布林部落的殘暴首領。',
    baseStats: {
      hp: D(500), mp: D(50),
      atk: D(40), def: D(25),
      matk: D(10), mdef: D(15),
      spd: D(8), lck: D(10),
      crit: D('0.1'), critDmg: D('2.0'),
      dodge: D('0.05'), acc: D('0.92'),
    },
    statScaling: 2.0,
    skillIds: [],
    lootTable: [
      { templateId: 'iron_sword', weight: 1.0, minQty: 1, maxQty: 1 },
      { templateId: 'iron_armor', weight: 0.8, minQty: 1, maxQty: 1 },
    ],
    goldDrop: [150, 350],
    xpReward: D(3000),
    tameable: false, tameRate: 0,
  },
  goblin_warlord: {
    id: 'goblin_warlord', name: '哥布林軍閥', family: 'humanoid', tier: 2, isBoss: true, isElite: false,
    description: '統率整個哥布林山谷的鐵腕軍閥。',
    baseStats: {
      hp: D(1200), mp: D(80),
      atk: D(65), def: D(40),
      matk: D(15), mdef: D(20),
      spd: D(10), lck: D(12),
      crit: D('0.12'), critDmg: D('2.1'),
      dodge: D('0.06'), acc: D('0.92'),
    },
    statScaling: 2.0,
    skillIds: [],
    lootTable: [
      { templateId: 'steel_sword', weight: 1.0, minQty: 1, maxQty: 1 },
      { templateId: 'chain_armor', weight: 0.8, minQty: 1, maxQty: 1 },
    ],
    goldDrop: [300, 700],
    xpReward: D(6000),
    tameable: false, tameRate: 0,
  },
  swamp_hydra: {
    id: 'swamp_hydra', name: '沼澤九頭蛇', family: 'beast', tier: 3, isBoss: true, isElite: false,
    description: '傳說中沼澤深處的多頭怪物，斬掉一頭會再長兩頭。',
    baseStats: {
      hp: D(4000), mp: D(200),
      atk: D(100), def: D(70),
      matk: D(60), mdef: D(40),
      spd: D(10), lck: D(8),
      crit: D('0.1'), critDmg: D('2.2'),
      dodge: D('0.05'), acc: D('0.9'),
    },
    statScaling: 2.2,
    skillIds: [],
    lootTable: [
      { templateId: 'battle_axe', weight: 0.8, minQty: 1, maxQty: 1 },
      { templateId: 'mystic_robe', weight: 0.7, minQty: 1, maxQty: 1 },
    ],
    goldDrop: [600, 1500],
    xpReward: D(12000),
    tameable: false, tameRate: 0,
  },
  iron_titan: {
    id: 'iron_titan', name: '鐵甲泰坦', family: 'construct', tier: 3, isBoss: true, isElite: false,
    description: '鐵山礦脈的最終守護者，以精鋼打造的不滅機械。',
    baseStats: {
      hp: D(6000), mp: D(0),
      atk: D(130), def: D(150),
      matk: D(0), mdef: D(80),
      spd: D(8), lck: D(5),
      crit: D('0.07'), critDmg: D('2.0'),
      dodge: D('0.02'), acc: D('0.9'),
    },
    statScaling: 2.2,
    skillIds: [],
    lootTable: [
      { templateId: 'great_sword', weight: 0.9, minQty: 1, maxQty: 1 },
      { templateId: 'dragon_mail', weight: 0.7, minQty: 1, maxQty: 1 },
    ],
    goldDrop: [1000, 2500],
    xpReward: D(25000),
    tameable: false, tameRate: 0,
  },
  volcano_lord: {
    id: 'volcano_lord', name: '火山魔君', family: 'elemental', tier: 5, isBoss: true, isElite: false,
    description: '統治火山地帶的強大元素精靈，化身為永恆的烈焰。',
    baseStats: {
      hp: D(12000), mp: D(3000),
      atk: D(200), def: D(120),
      matk: D(250), mdef: D(150),
      spd: D(15), lck: D(20),
      crit: D('0.15'), critDmg: D('2.5'),
      dodge: D('0.08'), acc: D('0.95'),
    },
    statScaling: 2.5,
    skillIds: [],
    lootTable: [
      { templateId: 'dragon_fang', weight: 0.7, minQty: 1, maxQty: 1 },
      { templateId: 'dragon_scale_armor', weight: 0.6, minQty: 1, maxQty: 1 },
    ],
    goldDrop: [3000, 7000],
    xpReward: D(60000),
    tameable: false, tameRate: 0,
  },
  dragon_patriarch: {
    id: 'dragon_patriarch', name: '龍族族長', family: 'dragon', tier: 6, isBoss: true, isElite: false,
    description: '龍峰的最高統治者，千年智慧與無盡力量的化身。',
    baseStats: {
      hp: D(30000), mp: D(8000),
      atk: D(500), def: D(350),
      matk: D(450), mdef: D(300),
      spd: D(25), lck: D(40),
      crit: D('0.18'), critDmg: D('2.8'),
      dodge: D('0.12'), acc: D('0.97'),
    },
    statScaling: 2.8,
    skillIds: [],
    lootTable: [
      { templateId: 'dragon_fang', weight: 1.0, minQty: 1, maxQty: 1 },
      { templateId: 'dragon_scale_armor', weight: 0.9, minQty: 1, maxQty: 1 },
    ],
    goldDrop: [8000, 20000],
    xpReward: D(120000),
    tameable: false, tameRate: 0,
  },
  ancient_dragon: {
    id: 'ancient_dragon', name: '遠古龍王', family: 'dragon', tier: 8, isBoss: true, isElite: false,
    description: '橫跨千年的傳說龍族，毀天滅地的存在。',
    baseStats: {
      hp: D(100000), mp: D(50000),
      atk: D(2000), def: D(1500),
      matk: D(1800), mdef: D(1200),
      spd: D(30), lck: D(50),
      crit: D('0.2'), critDmg: D('3.0'),
      dodge: D('0.15'), acc: D('0.98'),
    },
    statScaling: 3.0,
    skillIds: [],
    lootTable: [
      { templateId: 'dragon_fang', weight: 1.0, minQty: 1, maxQty: 1 },
      { templateId: 'dragon_scale_armor', weight: 0.7, minQty: 1, maxQty: 1 },
    ],
    goldDrop: [20000, 80000],
    xpReward: D(300000),
    tameable: false, tameRate: 0,
  },
}

export function getMonsterById(id: string): MonsterTemplate | undefined {
  return MONSTER_TEMPLATES[id]
}

export function getMonstersByTier(tier: number): MonsterTemplate[] {
  return Object.values(MONSTER_TEMPLATES).filter(m => m.tier === tier && !m.isBoss && !m.isElite)
}
