import type { EquipmentTemplate } from '../../types'

export const EQUIPMENT_TEMPLATES: EquipmentTemplate[] = [
  // ── 武器 ─────────────────────────────────────────
  { id: 'short_sword', name: '短劍', slot: 'weapon', minTier: 0,
    baseStatRanges: { atk: [5, 10], spd: [1, 3] },
    allowedRarities: ['Common', 'Uncommon', 'Rare'],
    description: '輕巧的近戰武器，適合初學者。' },
  { id: 'iron_sword', name: '鐵劍', slot: 'weapon', minTier: 1,
    baseStatRanges: { atk: [15, 25], def: [1, 3] },
    allowedRarities: ['Common', 'Uncommon', 'Rare', 'Epic'],
    description: '可靠的標準劍，平衡的攻守。' },
  { id: 'magic_staff', name: '魔法杖', slot: 'weapon', minTier: 0,
    baseStatRanges: { matk: [8, 16], mp: [10, 20] },
    allowedRarities: ['Common', 'Uncommon', 'Rare', 'Epic'],
    description: '蘊含魔力的施法杖。' },
  { id: 'shadow_dagger', name: '暗影匕首', slot: 'weapon', minTier: 2,
    baseStatRanges: { atk: [20, 35], spd: [5, 10], crit: [3, 8] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic', 'Legendary'],
    description: '在黑暗中閃光的致命利器。' },
  { id: 'great_sword', name: '巨劍', slot: 'weapon', minTier: 3,
    baseStatRanges: { atk: [50, 80], hp: [20, 40], critDmg: [10, 25] },
    allowedRarities: ['Rare', 'Epic', 'Legendary', 'Mythic'],
    description: '需要雙手揮舞的強力重劍。' },
  { id: 'dragon_fang', name: '龍牙劍', slot: 'weapon', minTier: 5,
    baseStatRanges: { atk: [200, 350], matk: [150, 250], crit: [10, 20] },
    allowedRarities: ['Legendary', 'Mythic', 'Transcendent'],
    description: '以龍牙鍛造的傳說武器。' },
  // ── 武器（中階）───────────────────────────────────
  { id: 'steel_sword', name: '鋼劍', slot: 'weapon', minTier: 1,
    baseStatRanges: { atk: [30, 50], def: [3, 8] },
    allowedRarities: ['Common', 'Uncommon', 'Rare', 'Epic'],
    description: '以精鋼鍛造的可靠長劍。' },
  { id: 'battle_axe', name: '戰斧', slot: 'weapon', minTier: 2,
    baseStatRanges: { atk: [45, 70], critDmg: [8, 18] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic', 'Legendary'],
    description: '重量型雙手戰斧，爆發力驚人。' },
  { id: 'fire_staff', name: '火焰法杖', slot: 'weapon', minTier: 2,
    baseStatRanges: { matk: [40, 65], mp: [20, 40], crit: [3, 8] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic', 'Legendary'],
    description: '蘊含火焰之力的強力法杖。' },
  { id: 'cursed_blade', name: '詛咒刃', slot: 'weapon', minTier: 3,
    baseStatRanges: { atk: [70, 110], spd: [8, 15], crit: [5, 12] },
    allowedRarities: ['Rare', 'Epic', 'Legendary', 'Mythic'],
    description: '被古老詛咒所浸染的邪惡利刃。' },
  { id: 'mountain_hammer', name: '山嶽重槌', slot: 'weapon', minTier: 3,
    baseStatRanges: { atk: [90, 140], hp: [40, 80], def: [10, 20] },
    allowedRarities: ['Rare', 'Epic', 'Legendary', 'Mythic'],
    description: '以山脈礦石鑄造的超重型戰槌。' },
  // ── 頭部 ─────────────────────────────────────────
  { id: 'leather_cap', name: '皮革帽', slot: 'head', minTier: 0,
    baseStatRanges: { def: [2, 5] },
    allowedRarities: ['Common', 'Uncommon'],
    description: '簡單的皮革頭盔。' },
  { id: 'iron_helm', name: '鐵盔', slot: 'head', minTier: 1,
    baseStatRanges: { def: [8, 14], hp: [10, 20] },
    allowedRarities: ['Common', 'Uncommon', 'Rare'],
    description: '標準鐵製頭盔。' },
  { id: 'steel_helm', name: '鋼盔', slot: 'head', minTier: 2,
    baseStatRanges: { def: [20, 32], hp: [25, 45] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic'],
    description: '精鋼打造的堅固頭盔。' },
  { id: 'mage_hood', name: '法師兜帽', slot: 'head', minTier: 2,
    baseStatRanges: { mdef: [15, 25], mp: [30, 60], matk: [5, 12] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic'],
    description: '增幅魔力的神秘兜帽。' },
  { id: 'dragon_helm', name: '龍盔', slot: 'head', minTier: 4,
    baseStatRanges: { def: [80, 130], mdef: [60, 100], hp: [80, 150] },
    allowedRarities: ['Epic', 'Legendary', 'Mythic', 'Transcendent'],
    description: '以龍骨打磨的傳奇頭盔。' },
  // ── 身體 ─────────────────────────────────────────
  { id: 'cloth_robe', name: '布袍', slot: 'body', minTier: 0,
    baseStatRanges: { mdef: [3, 7], mp: [5, 15] },
    allowedRarities: ['Common', 'Uncommon', 'Rare'],
    description: '魔法師的基本外袍。' },
  { id: 'iron_armor', name: '鐵甲', slot: 'body', minTier: 1,
    baseStatRanges: { def: [12, 20], hp: [20, 35] },
    allowedRarities: ['Common', 'Uncommon', 'Rare', 'Epic'],
    description: '堅固的鐵製胸甲。' },
  { id: 'chain_armor', name: '鎖鏈甲', slot: 'body', minTier: 2,
    baseStatRanges: { def: [28, 45], hp: [40, 70], spd: [2, 6] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic'],
    description: '靈活與防禦兼備的鎖鏈甲。' },
  { id: 'mystic_robe', name: '神秘袍', slot: 'body', minTier: 2,
    baseStatRanges: { mdef: [30, 50], mp: [60, 100], matk: [10, 20] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic', 'Legendary'],
    description: '蘊含古老魔法的神秘長袍。' },
  { id: 'dragon_mail', name: '龍紋鎧', slot: 'body', minTier: 4,
    baseStatRanges: { def: [120, 200], hp: [150, 250], mdef: [60, 100] },
    allowedRarities: ['Epic', 'Legendary', 'Mythic'],
    description: '龍族工匠以龍紋鋼鑄造的重甲。' },
  { id: 'dragon_scale_armor', name: '龍鱗甲', slot: 'body', minTier: 5,
    baseStatRanges: { def: [300, 500], mdef: [200, 350], hp: [500, 800] },
    allowedRarities: ['Legendary', 'Mythic', 'Transcendent'],
    description: '以龍鱗鍛造的傳說鎧甲。' },
  // ── 腿部 ─────────────────────────────────────────
  { id: 'leather_leggings', name: '皮革護腿', slot: 'legs', minTier: 0,
    baseStatRanges: { def: [2, 4], spd: [1, 3] },
    allowedRarities: ['Common', 'Uncommon'],
    description: '簡單的皮革護腿。' },
  { id: 'iron_leggings', name: '鐵製護腿', slot: 'legs', minTier: 1,
    baseStatRanges: { def: [10, 16], hp: [12, 22] },
    allowedRarities: ['Common', 'Uncommon', 'Rare'],
    description: '標準鐵製護腿。' },
  { id: 'chain_leggings', name: '鎖鏈護腿', slot: 'legs', minTier: 2,
    baseStatRanges: { def: [22, 36], hp: [30, 55], spd: [2, 5] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic'],
    description: '兼顧防禦與靈活的鎖鏈護腿。' },
  { id: 'dragon_greaves', name: '龍紋護腿', slot: 'legs', minTier: 4,
    baseStatRanges: { def: [80, 130], mdef: [50, 85], spd: [5, 12] },
    allowedRarities: ['Epic', 'Legendary', 'Mythic', 'Transcendent'],
    description: '傳說級別的龍紋護腿。' },
  // ── 靴子 ─────────────────────────────────────────
  { id: 'leather_boots', name: '皮靴', slot: 'feet', minTier: 0,
    baseStatRanges: { spd: [2, 5], dodge: [1, 3] },
    allowedRarities: ['Common', 'Uncommon'],
    description: '輕便的皮革靴子。' },
  { id: 'iron_boots', name: '鐵靴', slot: 'feet', minTier: 1,
    baseStatRanges: { def: [6, 10], spd: [1, 3], hp: [8, 15] },
    allowedRarities: ['Common', 'Uncommon', 'Rare'],
    description: '堅固的鐵製靴子。' },
  { id: 'enchanted_boots', name: '附魔靴', slot: 'feet', minTier: 2,
    baseStatRanges: { spd: [8, 15], dodge: [3, 8], lck: [3, 7] },
    allowedRarities: ['Rare', 'Epic', 'Legendary'],
    description: '施加速度附魔的神秘靴子。' },
  // ── 副手 ─────────────────────────────────────────
  { id: 'wooden_shield', name: '木盾', slot: 'offhand', minTier: 0,
    baseStatRanges: { def: [4, 8], hp: [5, 12] },
    allowedRarities: ['Common', 'Uncommon'],
    description: '簡單的木製圓盾。' },
  { id: 'iron_shield', name: '鐵盾', slot: 'offhand', minTier: 1,
    baseStatRanges: { def: [15, 25], hp: [20, 35], mdef: [5, 10] },
    allowedRarities: ['Common', 'Uncommon', 'Rare', 'Epic'],
    description: '堅固的鐵製大盾。' },
  { id: 'arcane_tome', name: '奧術典籍', slot: 'offhand', minTier: 2,
    baseStatRanges: { matk: [15, 28], mp: [30, 55], mdef: [10, 18] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic', 'Legendary'],
    description: '記載高級魔法的神秘典籍。' },
  // ── 飾品 ─────────────────────────────────────────
  { id: 'lucky_ring', name: '幸運戒', slot: 'ring', minTier: 0,
    baseStatRanges: { lck: [3, 8] },
    allowedRarities: ['Common', 'Uncommon', 'Rare'],
    description: '據說能帶來好運的戒指。' },
  { id: 'attack_ring', name: '戰士戒', slot: 'ring', minTier: 1,
    baseStatRanges: { atk: [6, 14], crit: [2, 5] },
    allowedRarities: ['Common', 'Uncommon', 'Rare', 'Epic'],
    description: '提升攻擊力的戰鬥戒指。' },
  { id: 'mana_ring', name: '魔力戒', slot: 'ring', minTier: 1,
    baseStatRanges: { matk: [6, 14], mp: [15, 30] },
    allowedRarities: ['Common', 'Uncommon', 'Rare', 'Epic'],
    description: '蓄積魔力的戒指。' },
  { id: 'dragon_ring', name: '龍族戒', slot: 'ring', minTier: 4,
    baseStatRanges: { atk: [30, 55], matk: [30, 55], crit: [5, 12] },
    allowedRarities: ['Epic', 'Legendary', 'Mythic', 'Transcendent'],
    description: '龍族工藝鑄造的稀世戒指。' },
  { id: 'power_amulet', name: '力量護符', slot: 'amulet', minTier: 1,
    baseStatRanges: { atk: [5, 12], matk: [5, 12] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic'],
    description: '蘊含力量能量的護符。' },
  { id: 'resistance_amulet', name: '抗性護符', slot: 'amulet', minTier: 2,
    baseStatRanges: { mdef: [15, 28], hp: [30, 60] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic'],
    description: '大幅提升魔法抗性的護符。' },
  { id: 'dragon_amulet', name: '龍族護符', slot: 'amulet', minTier: 4,
    baseStatRanges: { atk: [25, 45], matk: [25, 45], hp: [100, 200], lck: [10, 20] },
    allowedRarities: ['Epic', 'Legendary', 'Mythic', 'Transcendent'],
    description: '凝聚龍族精魂的傳說護符。' },
]

export const ITEM_PREFIXES: { id: string; name: string; bonusStat: string; bonusRange: [number, number] }[] = [
  { id: 'blazing', name: '灼熱的', bonusStat: 'matk', bonusRange: [5, 15] },
  { id: 'ancient', name: '遠古的', bonusStat: 'atk', bonusRange: [8, 20] },
  { id: 'swift', name: '迅捷的', bonusStat: 'spd', bonusRange: [3, 10] },
  { id: 'sturdy', name: '堅固的', bonusStat: 'def', bonusRange: [5, 15] },
  { id: 'lucky', name: '幸運的', bonusStat: 'lck', bonusRange: [5, 12] },
  { id: 'sharp', name: '鋒利的', bonusStat: 'crit', bonusRange: [2, 8] },
  { id: 'vital', name: '活力的', bonusStat: 'hp', bonusRange: [20, 60] },
  { id: 'arcane', name: '奧術的', bonusStat: 'mp', bonusRange: [15, 40] },
]

export const ITEM_SUFFIXES: { id: string; name: string; bonusStat: string; bonusRange: [number, number] }[] = [
  { id: 'destruction', name: '毀滅', bonusStat: 'atk', bonusRange: [10, 30] },
  { id: 'titan', name: '巨人', bonusStat: 'hp', bonusRange: [50, 150] },
  { id: 'shadow', name: '暗影', bonusStat: 'critDmg', bonusRange: [10, 30] },
  { id: 'divinity', name: '神聖', bonusStat: 'matk', bonusRange: [10, 25] },
  { id: 'void', name: '虛空', bonusStat: 'spd', bonusRange: [5, 15] },
  { id: 'fortune', name: '財富', bonusStat: 'lck', bonusRange: [8, 20] },
]
