import type { EquipmentTemplate } from '../../types'

export const EQUIPMENT_TEMPLATES: EquipmentTemplate[] = [
  // ── 武器 ─────────────────────────────────────────
  { id: 'short_sword', name: '短劍', slot: 'weapon', minTier: 0,
    baseStatRanges: { atk: [5, 10], spd: [1, 3] },
    allowedRarities: ['Common', 'Uncommon', 'Rare'],
    description: '輕巧的近戰武器，適合初學者。' },
  { id: 'iron_sword', name: '鐵劍', slot: 'weapon', minTier: 1,
    baseStatRanges: { atk: [15, 25], def: [1, 3] },
    allowedRarities: ['Common', 'Uncommon', 'Rare', 'Epic'],
    description: '可靠的標準劍，平衡的攻守。' },
  { id: 'magic_staff', name: '魔法杖', slot: 'weapon', minTier: 0,
    baseStatRanges: { matk: [8, 16], mp: [10, 20] },
    allowedRarities: ['Common', 'Uncommon', 'Rare', 'Epic'],
    description: '蘊含魔力的施法杖。' },
  { id: 'shadow_dagger', name: '暗影匕首', slot: 'weapon', minTier: 2,
    baseStatRanges: { atk: [20, 35], spd: [5, 10], crit: [3, 8] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic', 'Legendary'],
    description: '在黑暗中閃光的致命利器。' },
  { id: 'great_sword', name: '巨劍', slot: 'weapon', minTier: 3,
    baseStatRanges: { atk: [50, 80], hp: [20, 40], critDmg: [10, 25] },
    allowedRarities: ['Rare', 'Epic', 'Legendary', 'Mythic'],
    description: '需要雙手揮舞的強力重劍。' },
  { id: 'dragon_fang', name: '龍牙劍', slot: 'weapon', minTier: 5,
    baseStatRanges: { atk: [200, 350], matk: [150, 250], crit: [10, 20] },
    allowedRarities: ['Legendary', 'Mythic', 'Transcendent'],
    description: '以龍牙鍛造的傳說武器。' },
  // ── 頭部 ─────────────────────────────────────────
  { id: 'leather_cap', name: '皮革帽', slot: 'head', minTier: 0,
    baseStatRanges: { def: [2, 5] },
    allowedRarities: ['Common', 'Uncommon'],
    description: '簡單的皮革頭盔。' },
  { id: 'iron_helm', name: '鐵盔', slot: 'head', minTier: 1,
    baseStatRanges: { def: [8, 14], hp: [10, 20] },
    allowedRarities: ['Common', 'Uncommon', 'Rare'],
    description: '標準鐵製頭盔。' },
  // ── 身體 ─────────────────────────────────────────
  { id: 'cloth_robe', name: '布袍', slot: 'body', minTier: 0,
    baseStatRanges: { mdef: [3, 7], mp: [5, 15] },
    allowedRarities: ['Common', 'Uncommon', 'Rare'],
    description: '魔法師的基本外袍。' },
  { id: 'iron_armor', name: '鐵甲', slot: 'body', minTier: 1,
    baseStatRanges: { def: [12, 20], hp: [20, 35] },
    allowedRarities: ['Common', 'Uncommon', 'Rare', 'Epic'],
    description: '堅固的鐵製胸甲。' },
  { id: 'dragon_scale_armor', name: '龍鱗甲', slot: 'body', minTier: 5,
    baseStatRanges: { def: [300, 500], mdef: [200, 350], hp: [500, 800] },
    allowedRarities: ['Legendary', 'Mythic', 'Transcendent'],
    description: '以龍鱗鍛造的傳說鎧甲。' },
  // ── 飾品 ─────────────────────────────────────────
  { id: 'lucky_ring', name: '幸運戒', slot: 'ring', minTier: 0,
    baseStatRanges: { lck: [3, 8] },
    allowedRarities: ['Common', 'Uncommon', 'Rare'],
    description: '據說能帶來好運的戒指。' },
  { id: 'power_amulet', name: '力量護符', slot: 'amulet', minTier: 1,
    baseStatRanges: { atk: [5, 12], matk: [5, 12] },
    allowedRarities: ['Uncommon', 'Rare', 'Epic'],
    description: '蘊含力量能量的護符。' },
]

export const ITEM_PREFIXES: { id: string; name: string; bonusStat: string; bonusRange: [number, number] }[] = [
  { id: 'blazing', name: '灼熱的', bonusStat: 'matk', bonusRange: [5, 15] },
  { id: 'ancient', name: '遠古的', bonusStat: 'atk', bonusRange: [8, 20] },
  { id: 'swift', name: '迅捷的', bonusStat: 'spd', bonusRange: [3, 10] },
  { id: 'sturdy', name: '堅固的', bonusStat: 'def', bonusRange: [5, 15] },
  { id: 'lucky', name: '幸運的', bonusStat: 'lck', bonusRange: [5, 12] },
  { id: 'sharp', name: '鋒利的', bonusStat: 'crit', bonusRange: [2, 8] },
  { id: 'vital', name: '活力的', bonusStat: 'hp', bonusRange: [20, 60] },
  { id: 'arcane', name: '奧術的', bonusStat: 'mp', bonusRange: [15, 40] },
]

export const ITEM_SUFFIXES: { id: string; name: string; bonusStat: string; bonusRange: [number, number] }[] = [
  { id: 'destruction', name: '毀滅', bonusStat: 'atk', bonusRange: [10, 30] },
  { id: 'titan', name: '巨人', bonusStat: 'hp', bonusRange: [50, 150] },
  { id: 'shadow', name: '暗影', bonusStat: 'critDmg', bonusRange: [10, 30] },
  { id: 'divinity', name: '神聖', bonusStat: 'matk', bonusRange: [10, 25] },
  { id: 'void', name: '虛空', bonusStat: 'spd', bonusRange: [5, 15] },
  { id: 'fortune', name: '財富', bonusStat: 'lck', bonusRange: [8, 20] },
]
